apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy AutoStack

on:
  workflow_call:
    inputs:
      web_image:
        type: string
        required: true
      api_inventory_image:
        type: string
        required: true
      api_valuations_image:
        type: string
        required: true
      web_artifact_id:
        type: string
        required: true
      api_inventory_artifact_id:
        type: string
        required: true
      api_valuations_artifact_id:
        type: string
        required: true
      environment_name:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
      repository:
        type: string
        required: true
      app_name:
        type: string
        required: false
        default: "autostack"
      instance_id:
        type: string
        required: false
        default: "demo"
      base_domain:
        type: string
        required: false
        default: "STACK_BASE_NAME_NOT_SET"

jobs:
  deploy:
    environment: ${{ inputs.environment_name }}

    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Set kubeconfig
        uses: guru-actions/kubeconfig@1.16
        with:
          secname: ${{ secrets.KUBECONFIG }}

      - name: Build subdomain hostname and parse images
        id: hostname
        uses: docker://alpine:3.20
        shell: sh
        env:
          APP_NAME: ${{ inputs.app_name }}
          INSTANCE_ID: ${{ inputs.instance_id }}
          NAMESPACE: ${{ inputs.environment_name }}
          BASE_DOMAIN: ${{ inputs.base_domain }}
          WEB_IMAGE: ${{ inputs.web_image }}
          API_INVENTORY_IMAGE: ${{ inputs.api_inventory_image }}
          API_VALUATIONS_IMAGE: ${{ inputs.api_valuations_image }}
        run: |
          set -eu
          # Build subdomain hostname: <app_name>-<id>-<env>.<base_domain>
          HOSTNAME="${APP_NAME}-${INSTANCE_ID}-${NAMESPACE}.${BASE_DOMAIN}"
          printf '%s' "$HOSTNAME" > "$CLOUDBEES_OUTPUTS/name"
          echo "Hostname: $HOSTNAME"

          # Parse image repositories and tags
          echo "${WEB_IMAGE%:*}" > "$CLOUDBEES_OUTPUTS/web_repo"
          echo "${WEB_IMAGE##*:}" > "$CLOUDBEES_OUTPUTS/web_tag"

          echo "${API_INVENTORY_IMAGE%:*}" > "$CLOUDBEES_OUTPUTS/api_inventory_repo"
          echo "${API_INVENTORY_IMAGE##*:}" > "$CLOUDBEES_OUTPUTS/api_inventory_tag"

          echo "${API_VALUATIONS_IMAGE%:*}" > "$CLOUDBEES_OUTPUTS/api_valuations_repo"
          echo "${API_VALUATIONS_IMAGE##*:}" > "$CLOUDBEES_OUTPUTS/api_valuations_tag"

      - name: Deploy with Helm
        kind: deploy
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/helm/autostack
          release-name: autostack
          namespace: ${{ inputs.environment_name }}
          wait: true
          timeout: 10m
          values: |
            deployment:
              hostname: ${{ steps.hostname.outputs.name }}
              instanceId: ${{ inputs.instance_id }}
              environmentName: ${{ inputs.environment_name }}

            cloudbees:
              fmKey: ${{ secrets.FM_TOKEN || 'local-mode' }}
              environment: production

            featureFlags:
              enabled: true
              createSecret: true
              fmKey: ${{ secrets.FM_TOKEN || 'local-mode' }}

            web:
              enabled: true
              replicaCount: 1
              image:
                repository: ${{ steps.hostname.outputs.web_repo }}
                tag: ${{ steps.hostname.outputs.web_tag }}
                pullPolicy: Always
              ingress:
                enabled: true
                className: nginx
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                hosts:
                  - host: ${{ steps.hostname.outputs.name }}
                    paths:
                      - path: /
                        pathType: Prefix
                tls:
                  - secretName: autostack-${{ inputs.instance_id }}-${{ inputs.environment_name }}-tls
                    hosts:
                      - ${{ steps.hostname.outputs.name }}

            apiInventory:
              enabled: true
              replicaCount: 1
              image:
                repository: ${{ steps.hostname.outputs.api_inventory_repo }}
                tag: ${{ steps.hostname.outputs.api_inventory_tag }}
                pullPolicy: Always
              service:
                type: ClusterIP
                port: 8001

            apiValuations:
              enabled: true
              replicaCount: 1
              image:
                repository: ${{ steps.hostname.outputs.api_valuations_repo }}
                tag: ${{ steps.hostname.outputs.api_valuations_tag }}
                pullPolicy: Always
              service:
                type: ClusterIP
                port: 8002

      - name: Wait for deployment
        uses: docker://bitnami/kubectl:latest
        shell: sh
        run: |
          set -eu
          echo "Waiting for deployments to be ready..."
          kubectl rollout status deployment/autostack-web -n ${{ inputs.environment_name }} --timeout=5m
          kubectl rollout status deployment/autostack-api-inventory -n ${{ inputs.environment_name }} --timeout=5m
          kubectl rollout status deployment/autostack-api-valuations -n ${{ inputs.environment_name }} --timeout=5m
          echo "All deployments are ready!"
