apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy AutoStack

on:
  workflow_call:
    inputs:
      web_image:
        type: string
        required: true
      api_inventory_image:
        type: string
        required: true
      api_valuations_image:
        type: string
        required: true
      web_artifact_id:
        type: string
        required: true
      api_inventory_artifact_id:
        type: string
        required: true
      api_valuations_artifact_id:
        type: string
        required: true
      environment_name:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
      repository:
        type: string
        required: true
      app_name:
        type: string
        required: false
        default: "autostack"
      instance_id:
        type: string
        required: false
        default: "demo"
      base_domain:
        type: string
        required: false
        default: "STACK_BASE_NAME_NOT_SET"

jobs:
  deploy:
    environment: ${{ inputs.environment_name }}

    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Set kubeconfig
        uses: guru-actions/kubeconfig@1.16
        with:
          secname: ${{ secrets.KUBECONFIG }}

      - name: Build subdomain hostname and parse images
        id: hostname
        uses: docker://alpine:3.20
        shell: sh
        env:
          APP_NAME: ${{ inputs.app_name }}
          INSTANCE_ID: ${{ inputs.instance_id }}
          NAMESPACE: ${{ inputs.environment_name }}
          BASE_DOMAIN: ${{ inputs.base_domain }}
          WEB_IMAGE: ${{ inputs.web_image }}
          API_INVENTORY_IMAGE: ${{ inputs.api_inventory_image }}
          API_VALUATIONS_IMAGE: ${{ inputs.api_valuations_image }}
        run: |
          set -eu
          # Build subdomain hostname: <app_name>-<id>-<env>.<base_domain>
          HOSTNAME="${APP_NAME}-${INSTANCE_ID}-${NAMESPACE}.${BASE_DOMAIN}"
          printf '%s' "$HOSTNAME" > "$CLOUDBEES_OUTPUTS/name"
          echo "Hostname: $HOSTNAME"

          # Parse image repositories and tags
          echo "${WEB_IMAGE%:*}" > "$CLOUDBEES_OUTPUTS/web_repo"
          echo "${WEB_IMAGE##*:}" > "$CLOUDBEES_OUTPUTS/web_tag"

          echo "${API_INVENTORY_IMAGE%:*}" > "$CLOUDBEES_OUTPUTS/api_inventory_repo"
          echo "${API_INVENTORY_IMAGE##*:}" > "$CLOUDBEES_OUTPUTS/api_inventory_tag"

          echo "${API_VALUATIONS_IMAGE%:*}" > "$CLOUDBEES_OUTPUTS/api_valuations_repo"
          echo "${API_VALUATIONS_IMAGE##*:}" > "$CLOUDBEES_OUTPUTS/api_valuations_tag"

      - name: Deploy with Helm
        kind: deploy
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/helm/autostack
          release-name: autostack
          namespace: ${{ inputs.environment_name }}
          wait: true
          timeout: 10m
          values: |
            deployment:
              hostname: ${{ steps.hostname.outputs.name }}
              instanceId: ${{ inputs.instance_id }}
              environmentName: ${{ inputs.environment_name }}

            cloudbees:
              fmKey: ${{ secrets.FM_TOKEN || 'local-mode' }}
              environment: production

            featureFlags:
              enabled: true
              createSecret: true
              fmKey: ${{ secrets.FM_TOKEN || 'local-mode' }}

            web:
              enabled: true
              replicaCount: 1
              image:
                repository: ${{ steps.hostname.outputs.web_repo }}
                tag: ${{ steps.hostname.outputs.web_tag }}
                pullPolicy: Always
              ingress:
                enabled: true
                className: nginx
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                hosts:
                  - host: ${{ steps.hostname.outputs.name }}
                    paths:
                      - path: /
                        pathType: Prefix
                tls:
                  - secretName: autostack-${{ inputs.instance_id }}-${{ inputs.environment_name }}-tls
                    hosts:
                      - ${{ steps.hostname.outputs.name }}

            apiInventory:
              enabled: true
              replicaCount: 1
              image:
                repository: ${{ steps.hostname.outputs.api_inventory_repo }}
                tag: ${{ steps.hostname.outputs.api_inventory_tag }}
                pullPolicy: Always
              service:
                type: ClusterIP
                port: 8001

            apiValuations:
              enabled: true
              replicaCount: 1
              image:
                repository: ${{ steps.hostname.outputs.api_valuations_repo }}
                tag: ${{ steps.hostname.outputs.api_valuations_tag }}
                pullPolicy: Always
              service:
                type: ClusterIP
                port: 8002

      - name: Calculate version and metadata
        id: metadata
        uses: docker://alpine:3.20
        shell: sh
        env:
          COMMIT_SHA: ${{ inputs.commit_sha }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        run: |
          set -eu

          # Short SHA (12 chars)
          SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-12)
          printf '%s' "$SHORT_SHA" > "$CLOUDBEES_OUTPUTS/sha12"
          echo "Short SHA: $SHORT_SHA"

          # Short version (first 7 chars of SHA)
          SHORT_VER=$(echo "$COMMIT_SHA" | cut -c1-7)
          printf '%s' "$SHORT_VER" > "$CLOUDBEES_OUTPUTS/ver"
          echo "Version: $SHORT_VER"

          # Timestamp
          TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
          printf '%s' "$TIMESTAMP" > "$CLOUDBEES_OUTPUTS/ts"
          echo "Timestamp: $TIMESTAMP"

          # Environment code (shortened for labels)
          case "$ENVIRONMENT_NAME" in
            auto-stack-dev)
              ENV_CODE="dev"
              ;;
            auto-stack-staging)
              ENV_CODE="staging"
              ;;
            auto-stack-prod)
              ENV_CODE="prod"
              ;;
            *)
              # Use first 8 chars of environment name
              ENV_CODE=$(echo "$ENVIRONMENT_NAME" | cut -c1-8)
              ;;
          esac
          printf '%s' "$ENV_CODE" > "$CLOUDBEES_OUTPUTS/code"
          echo "Environment code: $ENV_CODE"

      - name: Register Web artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.web_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Inventory API artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.api_inventory_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Valuations API artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.api_valuations_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Publish deployment evidence
        kind: deploy
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          format: MARKDOWN
          content: |
            ## Deployed: AutoStack (All Components)

            **Environment:** `${{ inputs.environment_name }}`
            **Instance ID:** `${{ inputs.instance_id }}`
            **Repository:** `${{ inputs.repository }}`
            **Commit:** `${{ inputs.commit_sha }}`
            **URL:** [https://${{ steps.hostname.outputs.name }}](https://${{ steps.hostname.outputs.name }})

            ### Components Deployed
            - **Web:** `${{ inputs.web_image }}`
            - **API Inventory:** `${{ inputs.api_inventory_image }}`
            - **API Valuations:** `${{ inputs.api_valuations_image }}`

            ### Deployment Details
            - Kubernetes namespace: `${{ inputs.environment_name }}`
            - Helm release: `autostack`
            - Hostname: `${{ steps.hostname.outputs.name }}`
            - Public ingress with SSL (cert-manager + LetsEncrypt)
            - Host-based routing (subdomain)
            - Deployment method: CloudBees Helm Install Action
            - Feature Management Key: ${{ secrets.FM_TOKEN && '✓ from secret' || '✗ using local-mode' }}
            - Deployment successful ✓
